var jobList = [
  {
    image: "../Imagenes/photosnap.svg",
    logoName: "Photosnap",
    tags1: ["NEW!", "FEATURED"],
    title: "Senior Frontend Developer",
    specifics: ["1d ago • Full Time • USA only"],
    tags2: ["Frontend", "Senior", "HTML", "CSS", "JavaScript"],
  },
  {
    image: "../Imagenes/manage.svg",
    logoName: "Manage",
    tags1: ["NEW!", "FEATURED"],
    title: "Senior Frontend Developer",
    specifics: "1d ago • Part Time • Remote",
    tags2: ["Fullstack", "Midweight", "Python", "CSS", "React"],
  },
  {
    image: "../Imagenes/account.svg",
    logoName: "Account",
    tags1: ["NEW!"],
    title: "Junior Frontend Developer",
    specifics: "2d ago • Part Time • USA only",
    tags2: ["Frontend", "Senior", "HTML", "CSS", "JavaScript"],
  },
  {
    image: "../Imagenes/myhome.svg",
    logoName: "MyHome",
    tags1: [],
    title: "Junior Frontenbd Developer",
    specifics: "5d ago • Contract • USA only",
    tags2: ["Frontend", "Junior", "CSS", "JavaScript"],
  },
  {
    image: "../Imagenes/loop-studios.svg",
    logoName: "Loop Studios",
    tags1: [],
    title: "Junior Frontenbd Developer",
    specifics: "1w ago • Full Time • worldwide",
    tags2: ["Fullstack", "Midweight", "JavaScript", "Sass", "Ruby"],
  },
  {
    image: "../Imagenes/faceit.svg",
    logoName: "FaceIt",
    tags1: [],
    title: "Junior Backend Developer",
    specifics: "2w ago • Full Time • UK only",
    tags2: ["Backend", "junior", "Ruby", "RoR"],
  },
  {
    image: "../Imagenes/shortly.svg",
    logoName: "Shortly",
    tags1: [],
    title: "Junior Frontend Developer",
    specifics: "2w ago • Full Time • Worldwide",
    tags2: ["Frontend", "Junior", "HTML", "Sass" ,"JavaScript"],
  },
  {
    image: "../Imagenes/insure.svg",
    logoName: "Insure",
    tags1: [],
    title: "Junior Frontend Developer",
    specifics: "2w ago • Full Time •USA only",
    tags2: ["Frontend", "Junior", "Vue" ,"JavaScript", "Sass"],
  },
  {
    image: "../Imagenes/eyecam-co.svg",
    logoName: "Eyecam Co.",
    tags1: [],
    title: "Full Stack Engineer",
    specifics: "3w ago • Full Time • Worldwide",
    tags2: ["Fullstack", "Midweight", "JavaScript", "Django", "Python"],
  },
  {
    image: "../Imagenes/the-air-filter-company.svg",
    logoName: "The Ait Filter Company",
    tags1: [],
    title: "Front-end Dev",
    specifics: "1mo ago • Part Time • Worldwide",
    tags2: ["Frontend", "junior", "React", "Sass", "JavaScript"],
  },
];
export { jobList };  
